### ISSUE TITLE
[Feature Request] DS4 gyro simulation for DualShock 3 controller

### ISSUE THREAD

**Issue by eVenent** [schmaldeo/DS4Windows#1]
Cool project, can you add this commit from [sunnyqeen](https://github.com/sunnyqeen) to your fork? I always wanted DS3 with simulated gyro. https://github.com/Ryochan7/DS4Windows/pull/2944

___
**Update from [Beta](https://github.com/schmaldeo/DS4Windows/releases/tag/v3.6.0-beta.1):** Tested gyro aiming in Paladins and it works better than expected. It is possible to play with it and it helps with aiming. Playing Doom I + II is even better, because game uses only X axis so DS3 gyro works perfect there. Happy to have app which finally simulate gyro. Thanks once again!

You can add QoL feature that after selecting gyro simulation, virtual controller is changing from Xbox to DS4 and popup is informing about restart app. 🙂

___
_Adding it here, as it's better place for feature requests than [reddit](https://www.reddit.com/r/DS4Windows/comments/1exkvcc/comment/lj8i4hj/)._

**Comment by eVenent** [comment]
**Update from Beta 2:** Gyro works perfectly if you are not moving too much controller. It's even helping with aiming, so it's working fine already. But... Even if I set triggers to activate gyro as L2 or a different button, this option is not working but it would be useful to turn off/on gyro on demand. I believe it's not working because gyro translation is not remapping anything just translating DS3 to DS4 gyro signal. So even if I have configured things like below, gyro is always active (tested in Paladins). It's ok but to make  this feature more usable, toggling option would be cool.
![image](https://github.com/user-attachments/assets/74a46b58-7166-4f87-924f-3753c614b5fb)

If I will remap gyro to mouse, then all works fine and it's possible to use it on demand. :)

**Comment by schmaldeo** [comment]
I'll work on it and if everything goes well I'll release it today, otherwise on Monday :)).

**Comment by schmaldeo** [comment]
It should work in [this release](https://github.com/schmaldeo/DS4Windows/releases/tag/v3.6.0-beta.3). Let me know if it works as it should.

**Comment by eVenent** [comment]
Works exactly how I wanted. Thank you!

**Comment by schmaldeo** [comment]
Happy to hear that :) If you find any bugs, please open a new issue. I'm closing this one and if there are no bugs reported I will add this feature to the stable branch.
