### ISSUE TITLE
3.6.3 Not displaying HidHide mode on UI

### ISSUE THREAD

**Issue by Phantom2332** [schmaldeo/DS4Windows#10]
On latest update key mode is not displayed properly even after setting everything properly in HidHide,This also causes autoprofiles to don´t function properly.
![image](https://github.com/user-attachments/assets/f19e9e53-26c1-4554-8839-bd33a49a57ce)
![image](https://github.com/user-attachments/assets/4e61facb-668e-4b0c-8f96-ec8b5b0b3d46)
![image](https://github.com/user-attachments/assets/e5dd7d74-c669-4746-9564-e15f5b859488)
![image](https://github.com/user-attachments/assets/cea72238-0a8d-44c4-a916-33d140631ebf)

**Comment by schmaldeo** [comment]
It works just fine for me. Maybe check if you selected the correct controller in HidHide.
![image](https://github.com/user-attachments/assets/68a8b1ca-e095-49e4-9553-5e9ed6b7338e)
![image](https://github.com/user-attachments/assets/2d6e42c3-4edb-4ed9-8fa4-2f76ee490933)

**Comment by Phantom2332** [comment]
Nvm apparently my vigembus driver got corrupted,fresh installed and everything is working fine again!

Srry for the inconvenience and ty for your work!

**Comment by schmaldeo** [comment]
It's OK, happy it works for you again :)
