### ISSUE TITLE
DS4Windows is causing Apex Legends to crash.

### ISSUE THREAD

**Issue by Strive1s** [schmaldeo/DS4Windows#11]
I’m glad to see that DS4Windows is still being maintained, but now I’ve encountered an issue where using DS4Windows while playing APEX Legends on Steam causes the game to freeze. It might be related to the anti-cheat measures. Is there a way to resolve this problem?

**Comment by schmaldeo** [comment]
It wouldn't be the only game that suffers from collision of gamepad mappers with anti-cheat software (EA games are another example). Sadly I haven't got Apex Legends to check it out myself, but I'm leaving the issue open so if anyone else sees it and has an idea maybe they could help.

Usually with issues like this there's nothing to do with the code (maybe other than a complete rewrite of some core modules), but maybe there is a workaround.
