### ISSUE TITLE
[Feature request] Show profile switch as notification in Windows

### ISSUE THREAD

**Issue by Phantom2332** [schmaldeo/DS4Windows#12]
The current default implementation only shows a notification at first connection or on profile autoswitch,would be nice to also have the possibility using the profiles manually with each switch

**Comment by schmaldeo** [comment]
I'll be having a look after https://github.com/schmaldeo/DS4Windows/issues/6 is done :)

**Comment by schmaldeo** [comment]
A few questions regarding this request:

Do I understand it right that you want a notification like this:

![](https://i.imgur.com/MJWiKhf.png)

to be shown when you manually switch the profile of an active controller?

If so, I don't really see the reason for that if you switch it using this selector in the main window:

![](https://i.imgur.com/g2UFtUu.png)

as you can clearly see that it changed + it displays the change in the log. 
Adding a windows tray notification for this would require a change of the code that actually displays them (please note how if the DS4Windows window is active, you won't get a tray notification).

Another option is to display a notification when a profile is changed using an action triggered by a button and that would work BUT that can be a big interference if you're currently in a fullscreen game/app. 

Just let me know when you think it should actually be displayed.

**Comment by Phantom2332** [comment]
Yh im referring to when a "load profile" is used to load a macro 
![{CDBEDC8B-86EA-4469-9C3B-AFA87CB51997}](https://github.com/user-attachments/assets/f807e4e5-f734-4637-95b1-1ea4c445d6d2)
From that menu you can´t now that a profile is changed,its just loaded without notification, this is useful in case that the lightbar malfuncions or u are using a controller without lightbar, like when emulating a DS4 with susnshine,to be able to now which profile is in use without having to get into DS4 again.

Hope i clarified it now

**Comment by schmaldeo** [comment]
Yes, I'll add it as an option, it should be ready today or tomorrow.

**Comment by schmaldeo** [comment]
Available in [v3.7.4](https://github.com/schmaldeo/DS4Windows/releases/tag/v3.7.4).
