### ISSUE TITLE
[Feature Request] Show a battery indicator in the system tray

### ISSUE THREAD

**Issue by eVenent** [schmaldeo/DS4Windows#14]
I have found [this](https://github.com/Ryochan7/DS4Windows/issues/3223) feature request:
_Change the default icon or add a new one that shows the current battery level(digits)of the gamepad_

It may be useful to see battery level in taskbar as optional feature. I know that reWASD has such option.

**Comment by schmaldeo** [comment]
Available in [v3.8.0](https://github.com/schmaldeo/DS4Windows/releases/tag/v3.8.0).
