### ISSUE TITLE
[Feature Request] Hotkey for gyro recalibration

### ISSUE THREAD

**Issue by boomercore** [schmaldeo/DS4Windows#17]
Just thought it would be nice to be able to do this without several clicks into the app and away from whatever game you're playing.  If this was programmable to a chord of keys or gamepad buttons, even better.  Thanks in advance.

**Comment by schmaldeo** [comment]
I'll work on it this week. 
I'll try to add it as a special action so it's bindable to whatever button you want.

**Comment by schmaldeo** [comment]
It's ready but I want to release it together with https://github.com/schmaldeo/DS4Windows/issues/6 and https://github.com/schmaldeo/DS4Windows/issues/14 which would be tomorrow or in 2 days (unless you need this feature ASAP in which case just let me know and I'll release it alone).

Reason why i don't want to make another separate release is that lately I've been spamming releases and I don't think it's good.

**Comment by boomercore** [comment]
Whatever time suits you best. Thanks a lot for saving this project.

**Comment by schmaldeo** [comment]
Available in [v3.8.0](https://github.com/schmaldeo/DS4Windows/releases/tag/v3.8.0).

**Comment by boomercore** [comment]
Using 3.8.0 and thought I'd see if I understand the feature or if I communicated clearly:
This is the function I wanted to map:
![image](https://github.com/user-attachments/assets/72c7c906-6dff-42ea-bcf7-1fed6e5a8fb6)
which results in the gyro calibrating with a visual indicator here:
![image](https://github.com/user-attachments/assets/0b2e36b3-87b7-4f08-881a-e6652071aad5)

I'm looking in the Special Actions and the only thing related to anything gyro is the sixaxis wheel, set up as so:
![image](https://github.com/user-attachments/assets/7db88d97-088a-4e91-b7a5-813169e05854)  
This doesn't seem to give any indication it's calibrating like that button when I press it.

Did we have the same thing in mind?  Is this for something else?  Thanks for looking.

**Comment by schmaldeo** [comment]
Sorry, looks like the code responsible for it got lost somewhere in the merges (or maybe I forgot to merge it in general).

I'll re-add it and release a patch.

**Comment by schmaldeo** [comment]
Available in [3.8.1](https://github.com/schmaldeo/DS4Windows/releases/tag/v3.8.1) and sorry for that, literally thought i checked if everything is there and all was ok but apparently it wasn't :((

**Comment by boomercore** [comment]
You're doing great.  You should consider giving people a way to tip you somehow.

**Comment by schmaldeo** [comment]
There is an option for that on my GitHub profile :)
