### ISSUE TITLE
[Feature Request] Option to start in realtime priority

### ISSUE THREAD

**Issue by boomercore** [schmaldeo/DS4Windows#18]
I notice that dropped input is far less of an issue in realtime priority.  This cannot be forced via command line or shortcut options, it will be ignored when the app starts. As of now you can only do this manually each time you start it via task manager.  Thanks in advance.

**Comment by schmaldeo** [comment]
It's being worked on, should release it very soon.

**Comment by boomercore** [comment]
You are doing the lord's work.  Thanks.
