### ISSUE TITLE
[Feature Request] On "Special Actions" > "Press/Toggle key" add option to select controller buttons

### ISSUE THREAD

**Issue by Caio99BR** [schmaldeo/DS4Windows#21]
**Describe the feature request**
On Press/Toggle key add option to select the buttons of the controller and not just the keyboard

**To Reproduce**
1. Go to "Profiles" > "Edit" > "Special Actions" > "New Action" > "Press/Toggle key"
2. It shows only keyboard and mouse

**Expected behavior: Show this screen**
![image](https://github.com/user-attachments/assets/f634cdea-742a-4ed9-a9de-42bac8b8c12b)

**Current behavior**
![image](https://github.com/user-attachments/assets/72ff4346-90cf-4b3f-8e9a-58b367f6abde)

**Desktop:**
 - DS4Windows Version [3.8.1]

**Additional context**
I want to simulate touchpad actions on a PS3 controller using "Select" + "Another key" and I don't see another way to do it

**Comment by schmaldeo** [comment]
Could you not achieve it by recording a macro?

![](https://i.imgur.com/On0s1QN.png)

![](https://i.imgur.com/80i0LSp.png)

(Back is DS3 Select, DS4 Share)

**Comment by Caio99BR** [comment]
No, because I want to simulate the "Touchpad press" from PS4 controller
(And well I don't own a PS4 controller)

**Comment by schmaldeo** [comment]
OK, I'll work on it. As a temporary workaround if you want to have it now, create a macro that you want, use some different button instead of touchpad, go to your config directory (by default `%appdata%/DS4Windows/Profiles/name.json`), scroll down to `<Macro>` section and replace that button's ID with `286` (e.g. if you want to map Select to simple touchpad press, it should be:
```
<Macro>
   <Share>286/286</Share>
</Macro>
```
).

I reckon I'll work on it later this week, after I'm done with https://github.com/schmaldeo/DS4Windows/issues/20.

**Comment by Caio99BR** [comment]
Ah I see, I din't understand at first how Macro works but I did it.
Also it's located in a different place (`%appdata%/DS4Windows/Actions.xml`)

-> Another thing, if I try to do it on type `key` (`<Details>286</Details>`), the program will load it as `None`
-> If use `<Details>286/286</Details>` the program crash when trying to load the profile (well, not a problem since we shouldnt edit this file anyway)

![image](https://github.com/user-attachments/assets/3b8a34ae-41d6-4e2c-8d92-47ee0d0cceb2)

**Comment by Caio99BR** [comment]
I thing `Record a macro` should be something else like `Insert a macro` (but just an opinion, it's up to the user check the behavior of this option)

**Comment by schmaldeo** [comment]
If I'm honest I haven't thoroughly read through your feature request and automatically replied to it. I've made my first steps to make what you have requested and I reckon it will be available next week at latest.

**Comment by schmaldeo** [comment]
OK sorry for all the chaos. 

> I want to simulate touchpad actions on a PS3 controller using "Select" + "Another key" and I don't see another way to do it

What you want to do is:

1. Select a button in the main window
![](https://i.imgur.com/L3tShE7.png)
1. In bottom-left, select `Shift modifier`, choose Share (or whatever other button you want) as the modifier and press the touchpad on the controller image (or whatever other action you might want).
![](https://i.imgur.com/DVaRHZN.png)
1. Close the window and save

Let me know if that's what you wanted :)

The binding window in the action selector is not made for rebinding controller buttons to another controller buttons, you are meant to do that in the main window, like above.

**Comment by Caio99BR** [comment]
Ah I see, it's exactly what I wanted xD
... but it's not working as I expected

Since it's a Shift Modifier it keep the previous state of button used as Shift and release the state of Regular button:
B8: Select | B9: Start (as Shift) | B17: Touchpad Click
![image](https://github.com/user-attachments/assets/4b06ee6e-41da-4af0-bb76-8f6c1e3ca7cf)

The expected behavior should be like this (Using I as example), release both buttons:
![image](https://github.com/user-attachments/assets/ea3e99e8-37ab-41d0-ae17-82234b1e7282)

Of course the buttons used are pressed some times while using the combination but still works better than using Shift Modifier
![image](https://github.com/user-attachments/assets/ed935f09-3e73-45c1-abe8-188c7543c05d)

**Comment by schmaldeo** [comment]
Well, when the binding window is invoked from the special action editor, it's only meant to support KB+M. I was close to calling a wontfix on this issue, but I will work on it, just not sure how long it will take to complete considering that I've got to modify quite a lot of code for it to work this way.

**Comment by Caio99BR** [comment]
No no, if anything you can drop this, I thought the fix was simple (since I through part of code exist in the shift modifier)

**Comment by schmaldeo** [comment]
Sadly shift modifier is a whole different mechanism, special actions are a completely separate branch in the code (and some things about them are quite unfriendly to work with).

Could you confirm that I can abandon this issue?

**Comment by Caio99BR** [comment]
Yup
