### ISSUE TITLE
Rewrite all version checking code

### ISSUE THREAD

**Issue by schmaldeo** [schmaldeo/DS4Windows#25]
~~Figure out how changelog.json was generated.~~

~~Right now because of this when a new version is detected the part where the changelog should be is blank.~~

Instead rewriting all the code that checks for updates, etc., because some things in the one that's currently in place are atrocious.

**Comment by nefarius** [comment]
IIRC `DS4Windows/Changelog.json` was manually extended and checked in before each release.

**Comment by schmaldeo** [comment]
It did feel like it was either generated but the tool was missing from the repo or done manually, but it just didn't feel right with what the timestamps looked like 
(e.g.
```json
 {
      "version_str": "3.3.2",
      "release_date": "2023-12-23T18:36:38+0000",
      ...
}
```
)

Decided I'll probably rewrite all the code behind version and changelog checking to make use of GitHub's API and use the changelogs from releases.

Also, thanks for letting me know, I was going to message you about it somewhere but wasn't sure you would know anything about it :)

**Comment by nefarius** [comment]
> It did feel like it was either generated but the tool was missing from the repo or done manually, but it just didn't feel right with what the timestamps looked like

Fair enough, could be a tool that either was never released to the public **or** is hosted on Ryos Gitlab instead of Github.

> Also, thanks for letting me know, I was going to message you about it somewhere but wasn't sure you would know anything about it :)

IDK a ton but sure am available for whatever I can do if you wanna pick up the torch of this gaming behemoth :stuck_out_tongue_winking_eye:
