### ISSUE TITLE
[Bug] Hold Trigger multi-action is always executed over Tap Trigger with debouncing on

### ISSUE THREAD

**Issue by Ryusennin** [schmaldeo/DS4Windows#29]
For many years I've been using a "hold trigger" macro on my Share button to display RTSS.

With DS4W versions post-Ryochan, the hold macro is triggered by just tapping the Share button instead of holding it. If I assign a different function (like screenshot) to "tap trigger", both macros are activated simultaneously.

**Comment by schmaldeo** [comment]
Thank you for the report, I will investigate it in the upcoming days

**Comment by schmaldeo** [comment]
Seems like if you're using debouncing the detected key press is just a bit too long for it to detect it as a tap.

Temporary solution is to disable debouncing, I will work on a permanent solution that should be ready next week :)

**Comment by schmaldeo** [comment]
Fix was actually easier than expected, so available in [v3.9.1](https://github.com/schmaldeo/DS4Windows/releases/tag/v3.9.1) :)

**Comment by Ryusennin** [comment]
Thanks for looking into it.

I'm not sure the bug is entirely fixed. The hold trigger is now properly executed after a short holding period, but as soon as the button is released, it executes the same command again.

Talking about my previous RTSS example, the RTSS shortcut key is pressed after holding the Share button, but it is immediately pressed again when I release the Share button. Which means RTSS is displayed after the hold period, then switched off after releasing the hold button.

**Comment by schmaldeo** [comment]
OK, I will have a further look next week.

**Comment by schmaldeo** [comment]
Please check if it works as expected in [this beta](https://github.com/schmaldeo/DS4Windows/releases/tag/v3.9.2-beta.1).

**Comment by Ryusennin** [comment]
It is still very inconsistent.

For the record, I have 2 macros on the Share button:
1. "tap" trigger for screenshots (built-in Radeon driver screenshot function)
2. "hold" trigger for displaying a small RTSS overlay

Debouncing value is 20 ms.

With the latest beta, the first time I tap Share, it will correctly register the tap and take a screenshot. Holding then releasing Share will also display RTSS correctly.

But after that, it seems the behaviour of both triggers becomes erratic again. Most of the time a single tap will take either a screenshot, or switch on and off RTSS.

**Comment by schmaldeo** [comment]
I'm sorry but:
1. I am completely unable to reproduce that behaviour, even with higher debouncing
2. Any further modifications would basically require a rewrite of the method which I really don't want to commit to

In all fairness, I don't even see why something like that would be happening now, as any conditional statements that take elapsed time also account for debouncing. I'm going to add the changes from this beta to the next stable release but I'm not going to put any more work into this, mainly because I can't even reproduce it.

**Comment by Ryusennin** [comment]
That's understandable. I have personally no current need for debouncing, so this doesn't affect my daily use. The special actions are certainly more important to me. Still, those erratic interactions between debouncing and the hold trigger are puzzling.

Thanks anyway for looking into it 👍🏽

**Comment by schmaldeo** [comment]
Another thing is that the method that maps custom actions is quite a mess, but you can see how it's possible if you consider that some parts of it are from 2014 😛
