### ISSUE TITLE
[Feature Req] Action upon touching the touchpad

### ISSUE THREAD

**Issue by user18081972** [schmaldeo/DS4Windows#3]
**Describe the request**
For 3DS/DS emulation reasons, it would be useful for me, to have a custom action happening upon touching the touchpad, and upon no longer touching the touchpad.
It would allow me to bring the secondary DS screen to the forefront when i want to use it, and hide it when i dont. which saves me having to press a button again and again each time.

**Expected behavior**
A profile option that allows me to set, for example, pressing and releasing F7 upon putting my finger on the touchpad, and pressing and releasing F7 (maybe a seperate key could be usefull too) when lifting my finger from the touchpad. 

**Additional info**
The click action that is already part of DS4Windows wont work for me in this scenario, because i need the click action to actually press on the 3DS/DS screen.

**Comment by schmaldeo** [comment]
![h92b5CD](https://github.com/user-attachments/assets/438c80f3-56fc-49ac-bac4-d1b474968e40)
Is it basically supposed to work like this, where solid line is button pressed and no line is button not pressed?

**Comment by schmaldeo** [comment]
Well so basically what i said except you want it to work on a touch, not a press.

**Comment by schmaldeo** [comment]
@user18081972 now available in the [latest stable](https://github.com/schmaldeo/DS4Windows/releases/tag/v3.7.1).
