### ISSUE TITLE
Stick offset added by program on a Switch Pro controller

### ISSUE THREAD

**Issue by Siri-exe** [schmaldeo/DS4Windows#30]
https://github.com/schmaldeo/DS4Windows/issues/30#issuecomment-2402143831

**Comment by Siri-exe** [comment]
I have the latest version of ds4windows and I have tried reinstalling it but the issue still remains it didn’t use to happen when I first started using ds4 windows here is the issue 

Uploading 2024-10-09_17:38:46_video.mp4…

**Comment by schmaldeo** [comment]
1. Has that been an issue in Ryochan7's builds (pre-3.4.0 versions)?
2. What are your axis settings (
![](https://i.imgur.com/yDZdSNk.png)
)?

**Comment by Siri-exe** [comment]
Here are my axis settings

**Comment by schmaldeo** [comment]
It looks like it's already been brought up back when Ryochan maintained this application: https://github.com/Ryochan7/DS4Windows/issues/3119#issuecomment-1866757571

Also, sadly there's not much I can really do about it without having physical access to the hardware. Maybe try said calibration on Switch console (if you've got one)?

**Comment by Siri-exe** [comment]
Ok let me try calibrating it on my switch and I’ll tell you if it worked or not but thanks for your help and time!

**Comment by Siri-exe** [comment]
Hey I calibrated them and then tried it but nothing changed then I copied your axis settings and when I changed the anti dead zones it fixed itself , thanks a lot I appreciate your help

**Comment by schmaldeo** [comment]
No problem, that's what I'm here for 😀
