### ISSUE TITLE
DualSense connection error in Version 3.9.2-beta.2

### ISSUE THREAD

**Issue by redomCL** [schmaldeo/DS4Windows#32]
DualSense connection error in Version 3.9.2.
Version 3.9.1  no error.
log:
![QQ截图20241009211441](https://github.com/user-attachments/assets/fdc6fb4d-2c54-4add-aeea-731cd5c01c73)

**Comment by schmaldeo** [comment]
As a temporary fix, please revert back to 3.9.1.

@nefarius any ideas for why it would do this? No issue on DS4, also it's in the [write method](https://github.com/schmaldeo/DS4Windows/blob/master/DS4Windows/HidLibrary/HidDevice.cs#L196), just forgot to change the exception's message. Haven't got a DualSense to debug it myself, is there a chance the buffer is initialised with a wrong size? Doesn't make much sense considering it worked with streams + I haven't changed anything in how the buffer is set up.

**Comment by nefarius** [comment]
Can take a look when fit again, currently knocked out with the 'Rona.

**Comment by schmaldeo** [comment]
Alright take your time and hope you feel better soon 🙂

**Comment by nefarius** [comment]
@schmaldeo just tried it with a DS, can't reproduce it. @redomCL what exactly did you do to provoke this problem?

**Comment by redomCL** [comment]
> @schmaldeo 只是用 DS 试过了，无法重现。 @redomCL 您究竟做了什么来引发这个问题？

I just install this
![QQ截图20241016085856](https://github.com/user-attachments/assets/39133866-4e72-4fba-9fb3-f4509557a814)
my windows version:
![2](https://github.com/user-attachments/assets/7c151f40-7468-4348-887f-bdd1942f3dcf)
bluetooth:
intel ac9260 with bluetooth,driver version:
![3](https://github.com/user-attachments/assets/e78f5eec-cf9a-4b4d-a3fb-4bd4fef5627d)

Driver store explorer list:
![4](https://github.com/user-attachments/assets/d09eb45f-49ee-4fff-a66c-466b8f436c75)

**Comment by redomCL** [comment]
> @schmaldeo just tried it with a DS, can't reproduce it. @redomCL what exactly did you do to provoke this problem?

By the way,I had installed dshidmini driver 
![图片](https://github.com/user-attachments/assets/71786ff5-73f2-4600-af58-d35fbab2c76b)

**Comment by schmaldeo** [comment]
To me the thing that would seem most likely to cause it is the controller's software update, would be easiest to check if that's it if you had another pc/laptop. On another hand, the output buffer is initialised to a size that's fetched from the HID collection using `HidP_GetCaps()`, wouldn't really make sense for it to return wrong values? 

Anyway - really hard for me to say anything without having physical access to that hardware, if you've got another computer available, please check if the problem persists, maybe @nefarius could have some more ideas.

**Comment by redomCL** [comment]
I'm sorry, I didn't test the latest v3.9.3-beta.1 before. now I just tested this version and the problem has disappeared. This problem for me only exists in this version: https://github.com/schmaldeo/DS4Windows/releases/tag/v3.9.2-beta.2

**Comment by schmaldeo** [comment]
That's because these are 2 separate versions from separate branches - 3.9.3-beta.1 still uses the old FileStream-based I/O. In stable 3.9.3 the P/Invoke I/O will become the only available option, so it's important to make sure it works well on all devices.

**Comment by nefarius** [comment]
So..... Not an issue or...? I tested from master branch directly.

**Comment by schmaldeo** [comment]
3.9.3 beta is from `lightbar-macro`, 3.9.2 beta features are in master branch, so we're interested either in [this release](https://github.com/schmaldeo/DS4Windows/releases/tag/v3.9.2-beta.2) or alternatively in a self-compiled master. I've commited [these changes](https://github.com/schmaldeo/DS4Windows/commit/6aaa46a2a60fb3e28275c69f79a7a6961f237fdc) since that release but I'm certain these don't have any affect on this issue.

@redomCL as i said, checking if the issue persists on another machine with the same controller and [this version](https://github.com/schmaldeo/DS4Windows/releases/tag/v3.9.2-beta.2) would be a very important step towards fixing it for you.

**Comment by redomCL** [comment]
The same issues occurs on my other laptop 7300HQ intel ac 3160 with bluetooth
![QQ截图20241016232945](https://github.com/user-attachments/assets/b4b18073-2ccb-4e04-bb97-aa8b6a828079)

**Comment by schmaldeo** [comment]
Well it's related to the DS4 then, @nefarius have you ever updated your DualSense using that PlayStation Accessories app?

**Comment by nefarius** [comment]
> The same issues occurs on my other laptop 7300HQ intel ac 3160 with bluetooth,[v3.9.2-beta.2](https://github.com/schmaldeo/DS4Windows/releases/tag/v3.9.2-beta.2)

Just ran the specific build, no problems, see outdated FW in screenshot, next I will apply the update:

![image](https://github.com/user-attachments/assets/f1ab8da3-8fb9-4383-ba6c-f4889617460f)

**Comment by nefarius** [comment]
@schmaldeo everything works exactly the same after the FW update, can't reproduce:

![image](https://github.com/user-attachments/assets/48a8f9f2-11ed-400b-b051-366fc5bb9577)

Two ideas:
1. Ignore the exception (it is more of a sanity check anyway)
2. Log the size of the byte array passed in and the written value so we at least know how much it differs

Cheers

**Comment by nefarius** [comment]
> My DS has been updated to the latest firmware via PlayStation Accessories： ![5](https://private-user-images.githubusercontent.com/22269254/376849440-44c574e7-31eb-4eeb-b44b-bba95c0aef59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxOTkwNjcsIm5iZiI6MTcyOTE5ODc2NywicGF0aCI6Ii8yMjI2OTI1NC8zNzY4NDk0NDAtNDRjNTc0ZTctMzFlYi00ZWViLWI0NGItYmJhOTVjMGFlZjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDIwNTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmMmMzZTUzYmVjNDhiNzRkZjQ1YTZhZjdlZjMwODRlMzJlZDUzYjk1ZTVjYmJkNzNhOWRiN2FhMWZhZTcyNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hRPVWaRxAbQor5n1wBEuym4yC_3O1cja2VYjbRNcCWc)

@redomCL this doesn't show the actual version of your DS FW, it tells you to connect the controller, this is how it is supposed to look:

![image](https://github.com/user-attachments/assets/422a2de9-d657-41b4-81e6-be1bc5a30455)

Do you have a fake/aftermarket DS?

**Comment by redomCL** [comment]
> > My DS has been updated to the latest firmware via PlayStation Accessories： ![5](https://private-user-images.githubusercontent.com/22269254/376849440-44c574e7-31eb-4eeb-b44b-bba95c0aef59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxOTkwNjcsIm5iZiI6MTcyOTE5ODc2NywicGF0aCI6Ii8yMjI2OTI1NC8zNzY4NDk0NDAtNDRjNTc0ZTctMzFlYi00ZWViLWI0NGItYmJhOTVjMGFlZjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDIwNTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmMmMzZTUzYmVjNDhiNzRkZjQ1YTZhZjdlZjMwODRlMzJlZDUzYjk1ZTVjYmJkNzNhOWRiN2FhMWZhZTcyNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hRPVWaRxAbQor5n1wBEuym4yC_3O1cja2VYjbRNcCWc)
> 
> @redomCL this doesn't show the actual version of your DS FW, it tells you to connect the controller, this is how it is supposed to look:
> 
> ![image](https://private-user-images.githubusercontent.com/286631/377633413-422a2de9-d657-41b4-81e6-be1bc5a30455.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMTM3MDcsIm5iZiI6MTcyOTIxMzQwNywicGF0aCI6Ii8yODY2MzEvMzc3NjMzNDEzLTQyMmEyZGU5LWQ2NTctNDFiNC04MWU2LWJlMWJjNWEzMDQ1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQwMTAzMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmRhZDgwMjM1M2QxYTUzN2M2ODZiZmU5NTczMDg0ZGRmYzRhMzM0NTNjNTBmZjQxMzhjNDI3MDNjN2Q3MmY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4L5uhLevTuq2Wz2edRMVT7NFJoaNv0QYdSpzUL6tImg)
> 
> Do you have a fake/aftermarket DS?

no,it's real.I bought the DS earlier, and there were almost no fakes on the market at that time

**Comment by redomCL** [comment]
> @schmaldeo everything works exactly the same after the FW update, can't reproduce:
> 
> ![image](https://private-user-images.githubusercontent.com/286631/377632685-48a8f9f2-11ed-400b-b051-366fc5bb9577.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMTM5MzAsIm5iZiI6MTcyOTIxMzYzMCwicGF0aCI6Ii8yODY2MzEvMzc3NjMyNjg1LTQ4YThmOWYyLTExZWQtNDAwYi1iMDUxLTM2NmZjNWJiOTU3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQwMTA3MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjA1MDE4YWQ4MmU3YjQxMjZlYTRkZDk5NDViMTYzYjY4NDE4M2QxYzJjODRhOTFmMjg0NDg2Y2FkMmZkYzNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7DLV5YbWTydkqSrSZ-5rP1GDn8rEeaTysOnwDFsoSr4)
> 
> Two ideas:
> 
>     1. Ignore the exception (it is more of a sanity check anyway)
> 
>     2. Log the size of the byte array passed in and the written value so we at least know how much it differs
> 
> 
> Cheers

In my system,DS can't work on 3.9.2 beta2/(ㄒoㄒ)/~~

**Comment by schmaldeo** [comment]
In a few hours I'll build a version that does those 2 things mentioned and I'll need you to let me know if it works ok for you.

**Comment by redomCL** [comment]
> In a few hours I'll build a version that does those 2 things mentioned and I'll need you to let me know if it works ok for you.

OK! Thanks for your contributors!♥

**Comment by schmaldeo** [comment]
@redomCL Please download [this version](https://github.com/user-attachments/files/17430785/net8.0-windows.zip) and
1. See if it works
2. If it does, let it run for a minute, then export the log and send it here.

**Comment by redomCL** [comment]
> @redomCL Please download [this version](https://github.com/user-attachments/files/17430785/net8.0-windows.zip) and
> 
>     1. See if it works
> 
>     2. If it does, let it run for a minute, then export the log and send it here.

![图片](https://github.com/user-attachments/assets/d618151b-16cc-4558-aa58-7cd9e623884c)
it's working,I'll always run it until you get enough logs

**Comment by redomCL** [comment]
2024/10/18 下午4:59:08: DS4Windows version 3.9.2
2024/10/18 下午4:59:08: DS4Windows Assembly Architecture: x64
2024/10/18 下午4:59:08: OS Version: Microsoft Windows NT 10.0.19045.0
2024/10/18 下午4:59:08: OS Product Name: Windows 10 Pro for Workstations
2024/10/18 下午4:59:08: OS Release ID: 2009
2024/10/18 下午4:59:08: System Architecture: x64
2024/10/18 下午4:59:08: Running as User
2024/10/18 下午4:59:08: HidHide control device found
2024/10/18 下午4:59:09: 启动中
2024/10/18 下午4:59:11: Some applications may block controller inputs. (Windows UAC Conflictions). Please go to https://ryochan7.github.io/ds4windows-site/troubleshooting/kb-mouse-issues/#windows-not-responding-to-ds4ws-kb-m-commands-in-some-situations for more information and workarounds.
2024/10/18 下午4:59:11: Using output KB+M handler: SendInput
2024/10/18 下午4:59:11: Connection to ViGEmBus 1.21.442.0 established
2024/10/18 下午4:59:11: 寻找控制器中...
2024/10/18 下午4:59:11: 使用共享模式
2024/10/18 下午4:59:11: capabilities: 0
2024/10/18 下午4:59:11: capabilities: 0
2024/10/18 下午4:59:11: capabilities: 0
2024/10/18 下午4:59:11: capabilities: 0
2024/10/18 下午4:59:11: capabilities: 0
2024/10/18 下午4:59:11: capabilities: 0
2024/10/18 下午4:59:11: capabilities: 33
2024/10/18 下午4:59:11: capabilities: 0
2024/10/18 下午4:59:11: UDP server listening on address 127.0.0.1 port 26760
2024/10/18 下午4:59:22: capabilities: 0
2024/10/18 下午4:59:22: capabilities: 0
2024/10/18 下午4:59:22: capabilities: 547
2024/10/18 下午4:59:22: capabilities: 0
2024/10/18 下午4:59:22: capabilities: 0
2024/10/18 下午4:59:22: capabilities: 0
2024/10/18 下午4:59:22: capabilities: 0
2024/10/18 下午4:59:22: capabilities: 33
2024/10/18 下午4:59:22: capabilities: 0
2024/10/18 下午4:59:22: written 547
2024/10/18 下午4:59:22: 找到控制器： E8:47:3A:C7:79:D6 (BT) (DualSense).
2024/10/18 下午4:59:23: Plugging in virtual X360 controller (XInput slot #1) in output slot #1
2024/10/18 下午4:59:23: Associated input controller #1 (DualSense) to virtual X360 Controller in output slot #1
2024/10/18 下午4:59:23: 控制器 1 正在使用配置 "DS5"。电池电量为 100%
2024/10/18 下午4:59:23: written 547
2024/10/18 下午4:59:23: written 547
2024/10/18 下午4:59:24: written 547
2024/10/18 下午4:59:25: capabilities: 0
2024/10/18 下午4:59:25: capabilities: 0
2024/10/18 下午4:59:25: capabilities: 0
2024/10/18 下午4:59:25: capabilities: 547
2024/10/18 下午4:59:25: capabilities: 0
2024/10/18 下午4:59:25: capabilities: 0
2024/10/18 下午4:59:25: capabilities: 0
2024/10/18 下午4:59:25: capabilities: 0
2024/10/18 下午4:59:25: capabilities: 33
2024/10/18 下午4:59:25: capabilities: 0
2024/10/18 下午4:59:25: written 547

**Comment by redomCL** [comment]
[log 5：19.txt](https://github.com/user-attachments/files/17432009/log.5.19.txt)

**Comment by redomCL** [comment]
this version is ok for me [v3.9.2](https://github.com/schmaldeo/DS4Windows/releases/tag/v3.9.2)

log:

10/19/2024 02:47:53: DS4Windows version 3.9.2
10/19/2024 02:47:53: DS4Windows Assembly Architecture: x64
10/19/2024 02:47:53: OS Version: Microsoft Windows NT 10.0.19045.0
10/19/2024 02:47:53: OS Product Name: Windows 10 Pro for Workstations
10/19/2024 02:47:53: OS Release ID: 2009
10/19/2024 02:47:53: System Architecture: x64
10/19/2024 02:47:53: Running as User
10/19/2024 02:47:53: HidHide control device found
10/19/2024 02:47:54: Starting...
10/19/2024 02:47:56: Some applications may block controller inputs. (Windows UAC Conflictions). Please go to https://ryochan7.github.io/ds4windows-site/troubleshooting/kb-mouse-issues/#windows-not-responding-to-ds4ws-kb-m-commands-in-some-situations for more information and workarounds.
10/19/2024 02:47:56: Using output KB+M handler: SendInput
10/19/2024 02:47:56: Connection to ViGEmBus 1.21.442.0 established
10/19/2024 02:47:56: Searching for controllers...
10/19/2024 02:47:56: Using Shared Mode
10/19/2024 02:47:56: UDP server listening on address 127.0.0.1 port 26760
10/19/2024 02:48:04: 找到控制器： E8:47:3A:C7:79:D6 (BT) (DualSense).
10/19/2024 02:48:05: Plugging in virtual X360 controller (XInput slot #1) in output slot #1
10/19/2024 02:48:05: Associated input controller #1 (DualSense) to virtual X360 Controller in output slot #1
10/19/2024 02:48:05: Controller 1 is using Profile "DS5". Battery level is 100%

**Comment by nefarius** [comment]
@redomCL please replicate the screenshot I made from the accessories app.

**Comment by redomCL** [comment]
> @redomCL please replicate the screenshot I made from the accessories app.

![图片](https://github.com/user-attachments/assets/541d85f2-e1a7-4851-9b2b-b6b11983b9ec)
This?

**Comment by redomCL** [comment]
Dear schmaldeo,3.9.3 is ok too for me.thanks!
