### ISSUE TITLE
DualSense Controller Latency Spikes After Windows 11 24H2 Update

### ISSUE THREAD

**Issue by Evoden1** [schmaldeo/DS4Windows#35]
**Describe the bug**
Since I updated to Windows 11 24H2, I've been having some issues with my Dual Sense controller in DS4Windows. Every minute or so, the latency spikes, making the controller really laggy. Then it goes back to normal. This happens whether I'm using Bluetooth or a wired connection. I've already updated my Bluetooth driver, but the problem persists. It's really frustrating because the controller keeps having these laggy moments and then goes back to working fine.

**To Reproduce**
Just updated windows 11 and used hidhide 

**Expected behavior**
Works with no latency spikes

**Screenshots and Logs**
![image](https://github.com/user-attachments/assets/669204f8-d45d-4b8d-9f2a-73254cf24f9e)

[Log Link](https://gist.github.com/Evoden1/f8d31a21789bc3a132b2a575d29666af)

**Desktop (please complete the following information):**
 - DS4Windows Version [3.9.3-beta.1] and [Version 3.9.1]

**Comment by schmaldeo** [comment]
Have you, by any chance, got any other controllers (preferably DS4), to check whether
1. These lag spikes are still present with that controller
2. If so, do changes from [v3.9.2-beta.2](https://github.com/schmaldeo/DS4Windows/releases/tag/v3.9.2-beta.2) (which is different from 3.9.3-beta.1, to be clear) help, as that version changes how the program communicates with the controller

I'll try checking if it happens on a virtual machine for myself but that's got its own limitations + I haven't got a DualSense so we'll need to have a bit of cooperation 🙂
