### ISSUE TITLE
Save Where window cannot be closed

### ISSUE THREAD

**Issue by xLive** [schmaldeo/DS4Windows#36]
**Describe the bug**
When running DS4Windows for the first time, the **Save Where** window asks you to choose where your profile and settings should be saved. You cannot close this window using the **X** button. It can only be closed by selecting an option.

**To Reproduce**
1. Delete DS4Windows from **%appdata%** folder (if exists) to trigger the **Save Where** window
2. Run DS4Windows
3. Try to close the **Save Where** window using the **X** button

**Expected behavior**
The window should close when the **X** button is clicked.

**Screenshots and Logs**
No logs available.

https://github.com/user-attachments/assets/8a5182a0-606f-4e36-9c93-c4ddfa2ea81e

**Desktop (please complete the following information):**
 - Controller Make and Model: N/A
 - OS: Windows 10 Pro 22H2 (OS Build 19045.5011)
 - DS4Windows Version: 3.9.1 (IIRC, this bug has been around for years)

**Comment by schmaldeo** [comment]
It does indeed look like it's been around since 2019, presumably even supposed to work like this. I'll make it abort the choice and close the app. Should be released in the next patch, probably tomorrow.

**Comment by schmaldeo** [comment]
Fixed in [v3.9.2](https://github.com/schmaldeo/DS4Windows/releases/tag/v3.9.2)
