### ISSUE TITLE
[BUG]: DS4Windows Blocking Display Mode Change NVIDIA

### ISSUE THREAD

**Issue by zebranco** [schmaldeo/DS4Windows#38]
**DS4Windows Blocking Display Mode Change NVIDIA**

When the laptop is set to Automatic Display Mode Switch (Advanced Optimus or Hybrid Mode in my case through Nvidia control panel)
while DS4Windows is running auto switching is blocked.

My laptop is the Lenovo LOQ r7 7840hs RTX 4050.

![image](https://github.com/user-attachments/assets/b7730b04-9036-4b17-a026-537ae02ad4de)

**Expected behavior**
No problems when DS4Windows is not running.

Steps to reproduce
Select Automatic select in Manage display mode in NVidia control panel.
Have DS4Windows running

Attempt to start a 3D application or game. In my case I used 3DMark.

NVIDIA will attempt to switch GPUs several times but fail due to DS4Windows.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 11 Pro Build 24/H2
 - DS4Windows Version 3.0.3

**Additional context**
NVIDIA Display Driver Version 565.90
Amd software: adrenalin edition 24.10.1

**Comment by schmaldeo** [comment]
Does it give any more details on the problem if you click on that notification, or in some kind of a log perhaps?

**Comment by zebranco** [comment]
by clicking on the link the panel redirects me to this link https://www.nvidia.com/content/Control-Panel-Help/vLatest/en-us/index.htm#t=mergedProjects%2Fnvcpl%2FNVIDIA_Control_Panel.htm

Going to the 3D settings it says that Windows manages the video cards now
![image](https://github.com/user-attachments/assets/bb9ff8aa-7be5-4987-a9b4-5ed59a884114)

Going into windows settings it only works with applications that support the feature
![image](https://github.com/user-attachments/assets/3a254625-2551-42e0-ad2c-69c6f2145358)

**Comment by zebranco** [comment]
#https://github.com/dotnet/wpf/issues/9286

**Comment by schmaldeo** [comment]
wontfix, I did expect it to be an issue not related to this specific app as no part of it does any special rendering.
