### ISSUE TITLE
[Feature Request] Sunshine support

### ISSUE THREAD

**Issue by eVenent** [schmaldeo/DS4Windows#4]
Hello,

I saw in other recent [DS4Windows forks](https://github.com/Ryochan7/DS4Windows/forks?include=active&page=1&period=2y&sort_by=last_updated) that [Sunshine](https://github.com/LizardByte/Sunshine) support is one of the most important commit. Maybe it's worth to add some checkbox, where users can enable optional Sunshine support like they have in forks below:

https://github.com/Shev0/DS4Windows-Sunshine-support/commit/2dbac2b6f0d0030099f749dba9d16811630ee8de
https://github.com/BotAlejandro/DS4Windows/commit/09913e7afee6e989e7a292603eaa4173ed85fab7
https://github.com/ragestaker21/DS4Windowsmoonlight/commit/9abf11c1ae1c7465687efa0e7ec9d5cdd0fcbc43
https://github.com/galax20002/DS4Windows/commit/a718f3a2546673ef5d6ca559cccbd17cd4f07b29

**Comment by schmaldeo** [comment]
Should be released tomorrow or maybe even today in the evening :)
On another note, I know it's not the best place to ask this question, but could you please check your Reddit DMs :P

**Comment by schmaldeo** [comment]
The logic used in all those forks is faulty, when you reconnect a physical controller, the program will just keep detecting new devices, e.g.:

Normal behaviour:

https://github.com/user-attachments/assets/12f9639a-6f43-40c5-bc03-a75f9899346a

Behaviour with the faulty code:

https://github.com/user-attachments/assets/f7b96192-2394-4142-93e1-07281f177a63

I will investigate and try making it work properly but it might take longer than previously anticipated.

**Comment by schmaldeo** [comment]
A temporary solution that I will be adding to the newest beta is a 5-second detection cooldown which makes the program ignore the virtual devices that appear after the real one, however there are 2 tradeoffs:
1. 2 or more devices cannot connect at once, you need to wait for at least 5 seconds before connecting another controller
2. If you connected a controller during that 5 second cooldown, you will need to disconnect all connected devices and reconnect them one by one, respecting the cooldown.

This solution is temporary and should be ultimately replaced by code that actually detects whether or not the detected device should be added to the controllers list or not.

**Comment by schmaldeo** [comment]
Having tried the code on my laptop, I found out that I cannot replicate the behaviour from https://github.com/schmaldeo/DS4Windows/issues/4#issuecomment-2325040872, therefore I've decided to add that code as the default Moonlight support and kept https://github.com/schmaldeo/DS4Windows/issues/4#issuecomment-2326108768 as an optional, _Advanced Support_. 
I've created a [doc](https://github.com/schmaldeo/DS4Windows/blob/moonlight/doc/moonlight_support.md) explaining the differences, and [released a new beta version](https://github.com/schmaldeo/DS4Windows/releases/tag/v3.7.0-beta.2) with these features.

If there are no bugs reported related this feature this week, I'll close the issue.

**Comment by Phantom2332** [comment]
Advanced mode working perfectly here!

**Comment by markandgo** [comment]
> Advanced mode working perfectly here!
> 
> "Simple mode" gives me 8 controllers issue as expected in the documentation

Working great with a hacked Nintendo Switch and motion control.

**Comment by DanielAvinoam** [comment]
hey, just tried the advanced mode with the latest version of moonlight & sunshine and the controller isn't recognized.
Is there anything that needs to be adjusted in sunshine's settings? (besides emulating ds4 obviously)
