### ISSUE TITLE
Ability to add support for new gamepads

### ISSUE THREAD

**Issue by DvaMishkiLapa** [schmaldeo/DS4Windows#40]
Good afternoon!
I found your project, it seems your realization has gone a long way. Glad someone took the courage to develop this app!

I would like to ask, is there any possibility of adding support for new gamepads? I tried to find documentation on this, but I couldn't find anything. Looking at the source code, it's not obvious to me yet. Perhaps you can provide some guidance on this.

**Comment by schmaldeo** [comment]
If you create a more detailed issue on what controller you'd like to add, and collaborate on it with me (I'd need you to do some basic tasks like testing and running some programs to inspect the input report), I'm sure we could at least try something. I'll close this issue and if you've got a specific request, please create a new one :)
