### ISSUE TITLE
Multiple mouse input sources

### ISSUE THREAD

**Issue by user889252627** [schmaldeo/DS4Windows#41]
**Describe the bug**
When fakerinput is instaled the mouse can't be moved with the stick and the gyro (or touchpad) at the same time.

**To Reproduce**
Install fakerinput
:p

**Expected behavior**
This issue isn't specific to this version of ds4, it's kind of a global problem since the gyro and the stick should be able to control the mouse at the same time like without fakeriput.

**Screenshots and Logs**
not applicable

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 and 11
 - DS4Windows Version all versions but I've used ryochan v3.3.3 and v3.9.2 of this project

**Additional context**
No context but I just want to thank you for updating the ds4 project

**Comment by schmaldeo** [comment]
Issue related to fakerinput, wontfix, sorry :/
