### ISSUE TITLE
PS Vita like DualShock 4 support

### ISSUE THREAD

**Issue by DvaMishkiLapa** [schmaldeo/DS4Windows#42]
[Well, have it your way ;D](https://github.com/schmaldeo/DS4Windows/issues/40)

## What I'm trying to do

[I'm using the PS Vita as an emulation of the DualShock 4.](https://github.com/DvaMishkiLapa/VitaOxiPad)

In short, it's a client-server application where the PS Vita is the server and the PC is the client. It works through Vigem.

I'm not so much in need of support as I am in need of understanding why I don't fall under the DualShock 4 definition. I realize you and I are digging through a bunch of outdated code, but it's still interesting :D

I have the original DualShock 4. But I seem to be lacking a bit of theory in understanding exactly what DS4Windows is trying to learn about the gamepad to define it.

So, if PS Vita can get DS4Windows support, that would be cool for users.

## What I have so far

- Emulation with `vendor: 0x054C, product: 0x05C4` is possible, games and testers think it's a DualShock 4, but DS4Windows refuses to understand it;
- Emulation with `vendor: 0x054C, product: 0x09CC` is possible, games and testers think it is DualShock 4, but DS4Windows refuses to understand it.
- `vendor: 0x054C, product: 0x05C4` in Device instance path Windows 11: `HID\VID_054C&PID_05C4&REV_0100\2&302DF937&2&0000`;

<details>
  <summary>hardwaretester.com screenshot</summary>
  
![image](https://github.com/user-attachments/assets/4d42ec92-2b35-4414-bdda-5fe70b09620a)
  
</details>

**Comment by schmaldeo** [comment]
Probably going to be interested in what [this](https://github.com/Ryochan7/HidReportInspector/releases/tag/v0.0.3) gives you.

Also, as this is an exceptionally low priority request, I don't expect it to be ready in any foreseeable future (unless the implementation is simple).

**Comment by DvaMishkiLapa** [comment]
> Also, as this is an exceptionally low priority request
I realize this is a low priority. Perhaps you have some recommendations? I'm experimenting with editing the source code, but haven't had any success yet.

**Comment by DvaMishkiLapa** [comment]
Damn, I should have known better. It's working, thanks!

**Comment by schmaldeo** [comment]
It's OK not to know everything :)
This actually gave me an idea to rename sunshine support to something like _virtual controller support_, as it basically applies to every single program that uses ViGEm.
