### ISSUE TITLE
[Feature Request] Some sort of symbol (or simply "99") instead of "100" to signify full charge in the tray icon, to improve readability

### ISSUE THREAD

**Issue by RandomNerd1** [schmaldeo/DS4Windows#43]
Pretty simple/minor--a three-digit number gets a bit hard to read in the tray since the numbers are smaller than when it's two digits, so I'd prefer if something, whether just "99" or like a checkmark or something lol, were displayed instead, when the controller is fully charged.

**Comment by schmaldeo** [comment]
Changed in [3.9.3](https://github.com/schmaldeo/DS4Windows/releases/tag/v3.9.3)

**Comment by RandomNerd1** [comment]
Updating to 3.9.5 seems to have reverted this. Also maybe the fully charged "99" should be in green or something instead of red to make it more obvious it's not still charging?

**Comment by schmaldeo** [comment]
Will fix in a minute, sorry, I just git pulled because I was on another PC and it didn't sync the icon for some reason.

**Comment by schmaldeo** [comment]
[Should be good in this release](https://github.com/schmaldeo/DS4Windows/releases/tag/v3.9.6), please confirm.

**Comment by RandomNerd1** [comment]
Perfect, thanks for the quick response!
