### ISSUE TITLE
 [Feature Request] Add a button to export special actions

### ISSUE THREAD

**Issue by wojtulace** [schmaldeo/DS4Windows#44]
When exporting a profile, the special actions that it uses aren't saved in its xml. Therefore, the entire functionality of the profile is not recovered after importing the file. I've been told that special actions are saved in the application settings, perhaps inside the appdata folder.

Edit: Apparently, special actions are saved in the appdata folder as 'Actions.xml'.  Hence, my idea is to add a button somewhere to import/export them.

**Comment by schmaldeo** [comment]
Added in [3.9.4](https://github.com/schmaldeo/DS4Windows/releases/tag/v3.9.4)
