### ISSUE TITLE
AutoUpdate not working

### ISSUE THREAD

**Issue by kdpkke** [schmaldeo/DS4Windows#47]
Hello there. When I open the app, I always get an error message saying: "DS4Windows Updater: Failed to retrieve latest version". 
I had the v3.9.2 and I had this error, so I manually installed v3.9.4 but I still get it

**Comment by schmaldeo** [comment]
This is likely due to some kind of a network misconfiguration/issue on your side, I'll give you some troubleshooting ideas tomorrow.

**Comment by schmaldeo** [comment]
I'll need you to manually download [v3.9.5](https://github.com/schmaldeo/DS4Windows/releases/tag/v3.9.5).
After you've downloaded it, please export the log file:

![](https://i.imgur.com/ctTgq0J.png)

And upload it here for me to see what exactly is going wrong.

**Comment by kdpkke** [comment]
[DS4WindowsLog.txt](https://github.com/user-attachments/files/17791090/DS4WindowsLog.txt)

Here you go. I downloaded the 3.9.5 version as you asked and I uploaded the log. The only problem is that even if the software is set in English, some parts of the logs are in Italian (I don't know why). I'm a software engineer too, so if you need an hand in doing something more technical, I can try to help

**Comment by schmaldeo** [comment]
.NET runtime translates the exceptions to the language of your Windows installation, so if it is (or ever was) in Italian, these will be too. 

As for the exception - it's thrown [right here](https://github.com/schmaldeo/DS4Windows/blob/master/DS4Windows/DS4Control/ScpUtil.cs#L3317).

As for why it's thrown - well, try opening [this (the same URI that's being accessed by that method)](https://api.github.com/repos/schmaldeo/DS4Windows/releases/latest) in the browser. If it works - I don't really know why it wouldn't in the app.

**Comment by kdpkke** [comment]
I can successfully open the link (I see a JSON formatted text)! I tried to disable Bitdefender Antivirus too, but it still does not work

**Comment by schmaldeo** [comment]
Well, it's supposed to be a JSON text, are you getting a HTTP 200 if you open it in the browser then or no?

**Comment by kdpkke** [comment]
yep. I also tried with CURL in powershell with the command "curl -l https://api.github.com/repos/schmaldeo/DS4Windows/releases/latest" and I still get a HTTP 200

**Comment by schmaldeo** [comment]
Then it's really a mistery for me why it doesn't work if you can cURL it and it works normally for everyone I know.

**Comment by kdpkke** [comment]
Well, I just deleted the folder where I extracted it and I extracted the zip on the main disk drive and now it works properly. I don't get the error message anymore. I really don't know why this happened...

**Comment by schmaldeo** [comment]
Maybe it was some weird UAC issue then.
