### ISSUE TITLE
Profiles don't work properly with special actions

### ISSUE THREAD

**Issue by vsub** [schmaldeo/DS4Windows#48]
**Describe the bug**
It does not separate the special actions per profile
For example I have a "Defailt" profile that have all settings set to default and I have a special action that makes DS4Windows show me the current battery level with a message If I tilt the controller up.
When I run any game that I have a separate profile for it,DS4Windows is still showing me the controllers battery status when I tilt it up even tho when I go to the special actions for the profile I am currently using in the game,that special action is not enabled.

When I enable "show auto-profile debug messages",I do see that the program is switching to the correct profile
This problem does not exist with the original 3.3.3 version

**Expected behavior**
Don't activate special actions that are not set for the profile

**Desktop (please complete the following information):**
 - Controller Make and Model: Is DS4 clone,on the back of it it says Q300
 - OS: Win10 Home latest update
 - DS4Windows Version 3.9.6

**Comment by schmaldeo** [comment]
This doesn't really seem right as I don't think I've not modified any code responsible for what could cause that, but I'll have a look regardless.

**Comment by vsub** [comment]
I find what's wrong and yes,the behaviour is the same in the original version,sorry
It seems DS4Windows does not switch profiles if the program I am switching to(that have a custom profile)is running as admin and DS4Windows is not
