### ISSUE TITLE
Rumble motors appear to be reversed

### ISSUE THREAD

**Issue by shanebeeps** [schmaldeo/DS4Windows#50]
**Describe the bug**
When testing in DS4Windows, and feeling rumble in game, the Heavy appears to fire the Light, and vice-versa. This appears to be a known bug from a previous version, as seen here: https://forums.pcsx2.net/Thread-DS4Windows-yet-another-DualShock-4-driver-No-longer-under-active-development?pid=406311#pid406311

**To Reproduce**
Connect a DS4 controller to computer running DS4windows, go to Profiles, test Heavy and Light Rumble options. 

**Expected behavior**
Rumble to match light and heavy in game.

**Screenshots and Logs**
N/A

**Desktop (please complete the following information):**
 - Controller Make and Model: Moonlight virtual controller enabled with the virtual controller option in DS4W settings. HidHide set up to disable virtual controller from appearing in Windows otherwise.
 - OS: Windows 10 Pro 22H2
 - DS4Windows Version: 3.9.7

**Additional context**
N/A

**Comment by schmaldeo** [comment]
Well, it's the classic case of _it works for me_. One thing I can think of is maybe it's coded wrong for some controllers, it works fine with DS4 v1 and I'm almost certain it worked fine with DualSense. I'd need more data to fix it which I don't currently have.

**Comment by shanebeeps** [comment]
Yeah, there are so many factors in play it's probably impossible to diagnose easily on your end. I'll connect a legit DS controller and see if it's the GameSir G8+ as the source of the problem.

It might be an interesting feature add to have a swap option for rumble motors, but I'm sure you have enough on your plate.

**Comment by shanebeeps** [comment]
OK, more testing, if this is at all valuable to you:
- latest **Android** version of Moonlight connected to latest Sunshine, default controller settings, etc.
- No android stuff enabled like the controller driver checkbox, anything like that
- Samsung S23 Ultra
- Actual **DS5** controller connected directly to Samsung S23
- Connect to host computer via Moonlight on Android device
- Controller shows as DS4 v.1, output to Xbox360
- Under profiles -> edit -> other tab, the heavy rumble test feels much lighter than light rumble test

**Comment by schmaldeo** [comment]
Thank you. I just added a checkbox to inverse the rumble motors, it's ready to ship but I want to ship it together with https://github.com/schmaldeo/DS4Windows/issues/51 so it should be released some time this week :)

**Comment by schmaldeo** [comment]
I apologise for the delay, but due to poor health and complete lack of free time I wasn't able to do anything related to the project. The feature is available in [v3.9.8](https://github.com/schmaldeo/DS4Windows/releases/tag/v3.9.8).
