### ISSUE TITLE
[Feature Request] Change lightbar color in macro manager

### ISSUE THREAD

**Issue by eVenent** [schmaldeo/DS4Windows#6]
Hello, I would like to be able to set macros for changing lightbar color. 

For example, throwing nade (R1) is setting lightbar to red, then there is "waiting block" for 3,5 seconds and then lightbar is changing color for 1 second on white - because after this time nade is blowing. In this way I will have animation for throwing nades which is showing me that area is safe.

It's only my sugestion, but I think it can work like Insert Wait block in "Record A Macro" section.
![image](https://github.com/user-attachments/assets/9c5a51eb-8234-4920-923e-4a0209a746a7)
It will add "lighbar block" where we can set RGB color like it is when we are remapping buttons.
![image](https://github.com/user-attachments/assets/0c852cf8-35f4-4831-909a-5da62a627eb9)

In games, many easy actions are time related, so DS4Windows would be able to handle LED changing in this way. It can be used with granades, activating ultimate attacks, reviving teammates or even showing cooldown of used skills.

**Comment by schmaldeo** [comment]
Should start working on it at the end of next week.

**Comment by schmaldeo** [comment]
Would something like this where you can:
- choose between using solid lightbar or macro as button action
- add however many colours to the macro you want with whatever timespan
- delete whichever part you want by just selecting it in the list and pressing delete

satisfy your needs?

As for when the macro would run, I was thinking of adding a selection between when the button is pressed (state going from 0 to 1) or when it's released (state going from 1 to 0), don't know if there's a need for that?

I've done some work and I've got some good progress, just need to figure out how exactly the button settings are saved and read, but I'm sure I'll be on it soon.

![image of the lightbar macro creator window](https://i.imgur.com/Dug74gL.png)

On another note, any chance you could check reddit DM? 🙏

**Comment by schmaldeo** [comment]
I've got an important implementation question:
would you want it to have cancellation or for it to always run until the end, as in:

The macro lasts 1000ms, starts on a key press
- key is pressed, the macro starts running
- key is released and pressed again after 500 ms

Now the question in this situation is, should it 
 - just ignore the second press OR
 - stop the currently running macro and start a new one?
 
Queueing is definitely not an option in my opinion. I think this issue could be resolved in the future by adding a dropdown to select which option to choose, but for now I'd like to implement only one.

**Comment by eVenent** [comment]
I think stop the currently running macro and start a new one will be more acurate in majority of use cases. Ofc, dropdown to select would the the best, but for now it can work like this.

**Comment by eVenent** [comment]
Tested with my DualShock 4 v.2 and DualSense, and as always new feature works great! I like that after macro, lightbar is coming back to default color, so I don't have to think which color to set at the end. It's a really good job, thank you.

**Comment by schmaldeo** [comment]
Happy to hear that!
It should work with all controllers that have a supported lightbar (so DS4, DualSense and probably the supported replicas).
I'll be adding the shift modifier support, selection mentioned in https://github.com/schmaldeo/DS4Windows/issues/6#issuecomment-2360641000 and if there are no bugs reported I reckon it will be available in a stable release next week :))

**Comment by schmaldeo** [comment]
Available in [v3.8.0](https://github.com/schmaldeo/DS4Windows/releases/tag/v3.8.0).

Cancellation mentioned in https://github.com/schmaldeo/DS4Windows/issues/6#issuecomment-2360641000 has been ignored for now, I'm planning to address it in a future patch.

**Comment by schmaldeo** [comment]
Cancellation added in [3.9.3-beta.1](https://github.com/schmaldeo/DS4Windows/releases/tag/v3.9.3-beta.1), also made the responsible code much more friendly and much less spaghetti-like.

Please test and if everything is OK it will be added to the next latest stable.

**Comment by schmaldeo** [comment]
Finished in [v3.9.2](https://github.com/schmaldeo/DS4Windows/releases/tag/v3.9.2)
