### ISSUE TITLE
Is the site in "about" related?

### ISSUE THREAD

**Issue by pcrov** [schmaldeo/DS4Windows#8]
Is the ds4-windows site linked in the "about" for this repo related to this fork? I poked through it and it links back to a different, older fork that seems unmaintained.

![Screenshot 2024-09-08 213137](https://github.com/user-attachments/assets/d386b6c9-550d-46a5-9ad9-171bd5f9d6d4)

**Comment by schmaldeo** [comment]
I linked the website because it contains some relevant info like supported controllers and the _Get started_ page, however it's not maintained by me and it's not linked directly to this fork, so I might want to make a documentation page in the future and remove this website from _About_.

**Comment by schmaldeo** [comment]
Created a new docs website for this repo. It's available at [https://schmaldeo.github.io/DS4WindowsDocs/](https://schmaldeo.github.io/DS4WindowsDocs/).
